// Server-side helpers for the local blog editor. Dev-only — every API route
// that imports this must call devOnly() first.
import fs from "fs";
import path from "path";

export const POSTS_DIR = path.join(process.cwd(), "src", "data", "posts");
export const PUBLIC_DIR = path.join(process.cwd(), "public");

export function isProd() {
  return process.env.NODE_ENV !== "development";
}

const escBody = (s: string) =>
  s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

export function postFiles(): string[] {
  return fs
    .readdirSync(POSTS_DIR)
    .filter((f) => f.endsWith(".ts") && f !== "index.ts" && f !== "types.ts");
}

export function findFileBySlug(slug: string): string | null {
  for (const f of postFiles()) {
    const src = fs.readFileSync(path.join(POSTS_DIR, f), "utf8");
    const m = src.match(/slug:\s*"([^"]+)"/);
    if (m && m[1] === slug) return f;
  }
  return null;
}

export function writePost(p: {
  slug: string;
  title: string;
  date: string;
  summary: string;
  image: string;
  body: string;
}) {
  const q = (s: string) => JSON.stringify(s ?? "");
  const content = `import type { Post } from "./types";

export const post: Post = {
  slug: ${q(p.slug)},
  title: ${q(p.title)},
  date: ${q(p.date)},
  summary: ${q(p.summary)},
  image: ${q(p.image)},
  body: \`
${escBody(p.body.trim())}
\`,
};
`;
  fs.writeFileSync(path.join(POSTS_DIR, p.slug + ".ts"), content);
}

// Regenerates index.ts from whatever post files exist on disk.
export function regenIndex() {
  const files = postFiles().sort();
  const imports = files
    .map((f, i) => `import { post as p${i} } from "./${f.replace(/\.ts$/, "")}";`)
    .join("\n");
  const names = files.map((_, i) => `p${i}`).join(", ");
  const content = `// AUTO-GENERATED by the local editor (/editor) — regenerated on every save.
// Hand-editing still works: add a file in this folder and either re-save any
// post in the editor or add the import here yourself.
import type { Post } from "./types";
${imports}

export type { Post };

export const posts: Post[] = [${names}].sort(
  (a, b) => +new Date(b.date) - +new Date(a.date)
);

export function getPost(slug: string): Post | undefined {
  return posts.find((p) => p.slug === slug);
}
`;
  fs.writeFileSync(path.join(POSTS_DIR, "index.ts"), content);
}
