// AUTO-GENERATED by the local editor (/editor) — regenerated on every save.
// Hand-editing still works: add a file in this folder and either re-save any
// post in the editor or add the import here yourself.
import type { Post } from "./types";
import { post as p0 } from "./life_story";
import { post as p1 } from "./pyconusa26";
import { post as p2 } from "./scipy-2024-paper";

export type { Post };

export const posts: Post[] = [p0, p1, p2].sort(
  (a, b) => +new Date(b.date) - +new Date(a.date)
);

export function getPost(slug: string): Post | undefined {
  return posts.find((p) => p.slug === slug);
}
